//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTWebApiGetMethodd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quizonlineEntities1 : DbContext
    {
        public quizonlineEntities1()
            : base("name=quizonlineEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_question> tbl_question { get; set; }

        public int id { get; set; }

        public String question_content { get; set; }

        public DateTime create_date { get; set; }

        public int subject_id { get; set; }

        public int status_id { get; set; }
    }
}
